
version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - 3000:3000
    environment:
      - MONGODB_URI=mongodb://mongo:27017/pwnsecShop
      - PORT=3000
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

